FROM molssi/psi4v180-mamba141:latest
 
LABEL maintainer="Mohammad Mostafanejad, \
                  Molecular Sciences Software Institute"

COPY --from=molssi/ase322-mamba141:latest ${MAMBA_ROOT_PREFIX} ${MAMBA_ROOT_PREFIX}