FROM molssiai/psi4v18-mamba141-py310:5.23.2023
 
LABEL maintainer="Mohammad Mostafanejad, \
                  MolSSI-AI, Molecular Sciences Software Institute"

COPY --from=molssiai/ase322-mamba141-py310 /opt/conda /opt/conda